# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 09:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_diary', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 1, 4, 9, 1, 41, 262000, tzinfo=utc))),
            ],
        ),
    ]
